### PR TITLE
Extract cast and plot from description.

### PR DESCRIPTION
**Pull request by rgc99**
Added cast information which is embedded in the description.

### CODE REVIEW

**Comment by andybotting** [comment]
I'm tempted to leave this one, considering how few programs list the cast, and the information is still shown in the description. 

The more specific parsing we have, the more likely it will break when the ABC inevitably change the structure.

Are you OK with that?

**Comment by rgc99** [comment]
Sure, I understand. Can we keep the second commit which does two things. 1/ Adds the time to the expiry date (I need to know how many more hours I have) and 2/ Does not put the expiry on the plot outline. The Confluence skin expects a single line for the plot outline and the newline + expiry makes it look odd.

**Comment by rgc99** [comment]
Opps, wrong button.

**Comment by andybotting** [comment]
Yeah, sounds fine. I'll merge soon.

**Comment by andybotting** [comment]
I still haven't merged this :(

I'll make sure I do it in the next round of work.

**Pull request closed without merging**
